FROM node:18

ARG PORT
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DATABASE

ENV PORT $PORT
ENV POSTGRES_HOST $POSTGRES_HOST
ENV POSTGRES_PORT $POSTGRES_PORT
ENV POSTGRES_USER $POSTGRES_USER
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD
ENV POSTGRES_DATABASE $POSTGRES_DATABASE

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

EXPOSE $PORT
ENTRYPOINT ["npm", "start"]