FROM node:18

ARG PORT
ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG OPEN_DATA_SERVICE_KEY

ENV PORT $PORT
ENV MYSQL_HOST $MYSQL_HOST
ENV MYSQL_PORT $MYSQL_PORT
ENV MYSQL_USER $MYSQL_USER
ENV MYSQL_PASSWORD $MYSQL_PASSWORD
ENV MYSQL_DATABASE $MYSQL_DATABASE
ENV OPEN_DATA_SERVICE_KEY $OPEN_DATA_SERVICE_KEY

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build
RUN npm run typeorm -- migration:run -d src/config/data-source.ts

EXPOSE $PORT
ENTRYPOINT ["npm", "start"]